### ISSUE TITLE
Is it worth upgrading to Babel 6?

### ISSUE THREAD

**Issue by benji6** [eventualbuddha/rollup-starter-project#2]

**Comment by chadhietala** [comment]
I agree, I'm trying to figure out how this and things like https://github.com/rollup/rollup-plugin-babel and https://github.com/rollup/babel-preset-es2015-rollup fit together with Babel 6.

Updating the dependencies in this repo to use `babel-core` and changing the test command to look in `babel-core/register` yields an error because the modules are not transpiled.

**Comment by eventualbuddha** [comment]
Yep, I'll do it at some point or, if someone else figures it out, review a PR.
